### ISSUE TITLE
Output contains ANSI escape code if redirecting output to file

### ISSUE THREAD

**Issue by fangbinwei** [felixfbecker/cli-highlight#116]
**index.js**
```js
const highlight = require('cli-highlight').highlight
console.log(highlight('module.exports = {a: 1}', { language: 'js' }))
```

`node index.js > t.js`

output is 
```
[36mmodule[39m.exports = {[36ma[39m: [32m1[39m}
```

It's caused by https://github.com/felixfbecker/cli-highlight/commit/73847058ba1094a39fde416a081c95c761475104 according to https://github.com/vuejs/vue-cli/pull/6084#issuecomment-735719453

**Comment by felixfbecker** [comment]
Hmm I see, but this is somewhat intentional. https://github.com/felixfbecker/cli-highlight/commit/73847058ba1094a39fde416a081c95c761475104 aligned the code to the behavior that was always intended, which is the thought that if you use `cli-highlight` but don't want colored output, why would you use `cli-highlight`? This way it still works even when you redirect the output e.g. to a pager, to a log file being viewed with a viewer that supports colors, etc. You could for example use `cat t.js` to view the file with colors.

I see though that there is a use case for non-highlighted direction, so it's probably better to let the user force colors as needed with `--color`/`--no-color` and the `FORCE_COLOR` env var.

**Comment by fangbinwei** [comment]
Thanks a lot !!!
