### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by slinkardbrandon** [felixfbecker/cli-highlight#58]
Pending a fix from the open issue on a dependency of this project we'll need to update this repo to pull in their changes.
* https://github.com/highlightjs/highlight.js/issues/1990

**Comment by zackzachariah** [comment]
I think this issue has been fixed by highlightjs version 9.15.6 moving the offending dependencies to `devDependencies` (see [pull request here](https://github.com/highlightjs/highlight.js/pull/1995)). Updating this package to depend on 9.15.6 or greater should fix the vulnerabilities being pulled in from their build system.

**Comment by felixfbecker** [comment]
Since highlight.js is a floating range, no update should be needed in this repo

**Comment by zackzachariah** [comment]
@felixfbecker Quite right, my mistake. I thought that `package-lock.json` would lock the version for downstream dependers but I was incorrect. I think this can be marked as closed, then.
